//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContoraRealtor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentDemand
    {
        public int IdApartmentDemand { get; set; }
        public Nullable<int> MaxPrice { get; set; }
        public Nullable<int> MinPrice { get; set; }
        public string MaxFloor { get; set; }
        public string MinFlorr { get; set; }
    }
}
