//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContoraRealtor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseDemand
    {
        public int IdHouseDemand { get; set; }
        public Nullable<int> MaxSquare { get; set; }
        public Nullable<int> MinSquare { get; set; }
        public Nullable<int> MaxRoom { get; set; }
        public Nullable<int> MinRoom { get; set; }
        public Nullable<int> MaxFloor { get; set; }
        public Nullable<int> MinFloor { get; set; }
    }
}
