//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContoraRealtor
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public int idProperty { get; set; }
        public Nullable<int> IdAdress { get; set; }
        public Nullable<int> Idcoordinates { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Coordinates Coordinates { get; set; }
    }
}
